/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      // Custom breakpoint matching the existing max-width: 900px media query
      workspace: '900px',
    },
    extend: {
      colors: {
        border: "var(--color-border)",
        borderStrong: "var(--color-border-strong)",
        accent: "var(--color-accent)",
        accentHover: "var(--color-accent-hover)",
        coral: "var(--color-coral)",
        coralHover: "var(--color-coral-hover)",
        coralBg: "var(--color-coral-bg)",
        surface: "var(--color-surface)",
        surfaceSubtle: "var(--color-surface-subtle)",
        surfaceHover: "var(--color-surface-hover)",
        text: "var(--color-text)",
        textMuted: "var(--color-text-muted)",
        textFaint: "var(--color-text-faint)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        info: "var(--color-info)",
        danger: "var(--color-danger)",
        // Label colors (categorical palette)
        labelViolet: "var(--color-label-violet-bg)",
        labelMagenta: "var(--color-label-magenta-bg)",
        labelIndigo: "var(--color-label-indigo-bg)",
        labelOlive: "var(--color-label-olive-bg)",
        labelSand: "var(--color-label-sand-bg)",
        labelPlum: "var(--color-label-plum-bg)",
        // Status badge colors
        badgeLowBg: "var(--color-badge-low-bg)",
        badgeLowText: "var(--color-badge-low-text)",
        badgeMediumBg: "var(--color-badge-medium-bg)",
        badgeMediumText: "var(--color-badge-medium-text)",
        badgeHighBg: "var(--color-badge-high-bg)",
        badgeHighText: "var(--color-badge-high-text)",
        badgeUrgentBg: "var(--color-badge-urgent-bg)",
        badgeUrgentText: "var(--color-badge-urgent-text)",
      },
      borderWidth: {
        DEFAULT: "var(--border-subtle, 1px)",
        strong: "var(--border-strong, 1px)",
      },
      spacing: {
        "var(--space-1)": "var(--space-1)",
        "var(--space-2)": "var(--space-2)",
        "var(--space-3)": "var(--space-3)",
        "var(--space-4)": "var(--space-4)",
        "var(--space-5)": "var(--space-5)",
        "var(--space-6)": "var(--space-6)",
        "var(--space-7)": "var(--space-7)",
        "var(--space-8)": "var(--space-8)",
        "var(--space-9)": "var(--space-9)",
        // Tailwind-compatible aliases (gap, padding, etc.)
        0: "0px",
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.5rem",
        6: "2rem",
        7: "2.5rem",
        8: "3rem",
        9: "4rem",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
      },
      lineHeight: {
        tight: "1.15",
        normal: "1.5",
      },
      fontFamily: {
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        "var(--text-label)": "var(--text-label)",
        "var(--text-meta)": "var(--text-meta)",
        "var(--text-body)": "var(--text-body)",
        "var(--text-strong)": "var(--text-strong)",
        "var(--text-display)": "var(--text-display)",
        "var(--text-title)": "var(--text-title)",
        // Aliases
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        md: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.6rem" }],
        xl: ["1.25rem", { lineHeight: "1.75rem" }],
      },
    },
  },
  plugins: [],
}
